// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapidAuto.Vehicules.API.Data;

#nullable disable

namespace RapidAuto.Vehicules.API.Migrations
{
    [DbContext(typeof(VehiculeContext))]
    partial class VehiculeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RapidAuto.Vehicules.API.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeFabrication")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Constructeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dispo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NbSieges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Niv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicule");
                });
#pragma warning restore 612, 618
        }
    }
}
