// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapidAuto.Commandes.API.Data;

#nullable disable

namespace RapidAuto.Commandes.API.Migrations
{
    [DbContext(typeof(CommandeContext))]
    [Migration("20220104185319_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RapidAuto.Commandes.API.Model.EntCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVoiture")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
